// Generated by CoffeeScript 1.4.0
(function() {
  var ObservableArray;

  (function() {});

  (function() {});

  ObservableArray = (function() {

    function ObservableArray() {
      this.keys = [];
      this.values = [];
    }

    ObservableArray.prototype.push = function(value) {};

    return ObservableArray;

  })();

  $(function() {});

}).call(this);
