// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var Vm, vm;
    Vm = (function() {

      function Vm(name, dob) {
        var _this = this;
        this.name = new Rx.BehaviorSubject(name || 'no name');
        this.dob = new Rx.BehaviorSubject(dob || new Date);
        this.age = Rx.Observable.interval(1).select(function() {
          return (new Date - _this.dob.value) / 1000 / 60 / 60 / 24 / 365;
        });
      }

      return Vm;

    })();
    vm = new Vm('Christopher Harris', new Date('11/11/1989'));
    return sx.bind(vm);
  });

}).call(this);
