// Generated by CoffeeScript 1.4.0
(function() {
  var Contact, vm;

  Contact = (function() {

    function Contact(name, email) {
      if (name == null) {
        name = '';
      }
      if (email == null) {
        email = '';
      }
      this.name = new Rx.BehaviorSubject(name);
      this.email = new Rx.BehaviorSubject(email);
      this.isSelected = new Rx.BehaviorSubject(false);
      this.display = sx.computed({
        params: {
          name: this.name,
          email: this.email,
          time: Rx.Observable.interval(10).doAction(function() {
            return console.log('hot! check for leaks!');
          })
        },
        read: function(params) {
          params.name = params.name.trim();
          params.email = params.email.trim();
          if (params.name && params.email) {
            return "" + params.name + " <" + params.email + ">";
          }
          if (params.name) {
            return "" + params.name;
          }
          if (params.email) {
            return "" + params.email;
          }
          return params.time.toString();
        }
      });
    }

    return Contact;

  })();

  vm = {
    items: new ObservableArray,
    remove: function(data) {
      return vm.items.remove(data);
    },
    select: function(data) {
      return data.isSelected.onNext(!data.isSelected.value);
    },
    add: function() {
      var contact;
      contact = new Contact;
      return vm.items.push(contact);
    }
  };

  $(function() {
    return sx.bind(vm);
  });

}).call(this);
